'''Controls the Flask Interface (GUI game)
'''
import json

from flask import Flask
from flask import request
from flask import render_template
from flask import jsonify
from flask import redirect, url_for
# from engine import get_year_list
# from engine import companies
from v2 import date_list
from v2 import companies
from v2 import timeIncriment, weekLoop, stock_change
from money import user_money, addMoney, removeMoney
# from engine import global_timer

app = Flask(__name__)
time = 0

# Define Plot Data 
#year = [1,2,3,4,5,6,7,8,9,10]
 
#  This data should be generated by some function
#value = [0, 10, 15, 8, 22, 18, 25,200,6,34]

current_company = "henriks"
event_description = ""

@app.route('/', methods = ['GET', 'POST'])
def main_runner():
    '''Runs placement page, allows player to place ships.
    '''
    # Instantiate the players board and basic ships 

    # Function that returns str, int int
    # yIn, vIn, event = onEvent()

    yIn = 'December'
    vIn = 30
    event = "This is an eventnasghausfghadflughadfghaflighadfgil"

    """year.append(yIn)
    value.append(vIn)"""
    new_event = event

    # Change this to be some sort of json, depending on others?
    company_information=companies[current_company]

    # user_money 

    # Return the components to the HTML template 
    return render_template(
        template_name_or_list="main.html",
        name_in=current_company,
        description_in=company_information["description"],
        xData_in=date_list,
        yData_in=company_information["values_list"],
        new_event=event_description,
        user_money=user_money,
        investment_in=company_information["stock-owned"]
    )

@app.route('/timer_button', methods = ['GET', 'POST'])
def timer_button():
    company_jsons = ["henrik's_department_store.json", "infinity_corp.json", "palmer_tech.json", "jojo_corp.json"]
    timeIncriment()
    for comp in company_jsons:
        weekLoop(comp)
    stock_change()
    return redirect(url_for('main_runner'))

# REDIRECTS - USED TO CHANGE PAGE ELEMENTS BECAUSE I CAN'T USE FLASK PROPERLY
    
@app.route('/henriks_redirect', methods = ['GET', 'POST'])
def henriks_redirect():
    if request.method == 'POST':
        global current_company
        current_company = "henriks"
        print(current_company)
    return redirect(url_for('main_runner'))

@app.route('/infinity_redirect', methods = ['GET', 'POST'])
def infinity_redirect():
    if request.method == 'POST':
        global current_company
        current_company = "infinity"
        print(current_company)
    return redirect(url_for('main_runner'))

@app.route('/palmer_redirect', methods = ['GET', 'POST'])
def palmer_redirect():
    if request.method == 'POST':
        global current_company
        current_company = "palmer"
        print(current_company)
    return redirect(url_for('main_runner'))

@app.route('/jojo_redirect', methods = ['GET', 'POST'])
def jojo_redirect():
    if request.method == 'POST':
        global current_company
        current_company = "jojo"
        print(current_company)
    return redirect(url_for('main_runner'))

@app.route('/money_in_redirect', methods = ['GET', 'POST'])
def money_in_redirect():
    if request.method == 'POST':
        global user_money
        global companies
        user_money, companies[current_company]["stock_value"] = addMoney(user_money, companies[current_company]["stock_value"])
        companies[current_company]["stock-owned"] -= 1
        print(companies[current_company]["stock-owned"] )

        company_jsons = ["henrik's_department_store.json", "infinity_corp.json", "palmer_tech.json", "jojo_corp.json"]
        timeIncriment()
        for comp in company_jsons:
             description = weekLoop(comp)
        stock_change()
    return redirect(url_for('main_runner'))

@app.route('/money_out_redirect', methods = ['GET', 'POST'])
def money_out_redirect():
    if request.method == 'POST':
        global user_money, description
        global companies
        user_money, companies[current_company]["stock_value"] = removeMoney(user_money, companies[current_company]["stock_value"])
        companies[current_company]["stock-owned"] += 1
        print(companies[current_company]["stock-owned"] )

        company_jsons = ["henrik's_department_store.json", "infinity_corp.json", "palmer_tech.json", "jojo_corp.json"]
        timeIncriment()
        for comp in company_jsons:
            description = weekLoop(comp)
        stock_change()
    return redirect(url_for('main_runner'))


if __name__ == '__main__':
    app.run(port=1111)
